// eslint.config.js
import { defineConfig, globalIgnores } from 'eslint/config';

import config from './index.js';

export default defineConfig([
  // Generated by release-it
  globalIgnores(['CHANGELOG.md']),
  {
    extends: [config]
  }
]);
